name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-venv git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/^title = .*/title = Melanfishing/' buildozer.spec
          sed -i 's/^package.name = .*/package.name = melanfishing/' buildozer.spec
          sed -i 's/^package.domain = .*/package.domain = org.example/' buildozer.spec
          sed -i 's|^source.dir = .*|source.dir = .|' buildozer.spec
          sed -i 's|^requirements = .*|requirements = python3, pygame|' buildozer.spec
          echo "source.include_exts = py,png,jpg,jpeg,mp3,ogg,wav,ttf" >> buildozer.spec
          echo "orientation = landscape" >> buildozer.spec
          echo "fullscreen = 1" >> buildozer.spec
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: melanfishing-apk
          path: bin/*.apk
